name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install
      - name: Run tests
        run: pipenv run python -m unittest discover 2> tests_output.txt
      - name: Upload ouput
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: tests-output
          path: tests_output.txt
